<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<h2 class="contentTitle">薪资表查看页面</h2>
<div class="pageContent">
	
	<div class="viewInfo" layoutH="97">
		<dl>
			<dt>员工：</dt><dd>${obj.employeeId}</dd>
		</dl>
		<dl>
			<dt>账套：</dt><dd>${obj.accountId}</dd>
		</dl>
		<dl>
			<dt>薪资日期：</dt><dd>${obj.salaryDate}</dd>
		</dl>
		<dl>
			<dt>col00：</dt><dd>${obj.col00}</dd>
		</dl>
		<dl>
			<dt>col01：</dt><dd>${obj.col01}</dd>
		</dl>
		<dl>
			<dt>col02：</dt><dd>${obj.col02}</dd>
		</dl>
		<dl>
			<dt>col03：</dt><dd>${obj.col03}</dd>
		</dl>
		<dl>
			<dt>col04：</dt><dd>${obj.col04}</dd>
		</dl>
		<dl>
			<dt>col05：</dt><dd>${obj.col05}</dd>
		</dl>
		<dl>
			<dt>col06：</dt><dd>${obj.col06}</dd>
		</dl>
		<dl>
			<dt>col07：</dt><dd>${obj.col07}</dd>
		</dl>
		<dl>
			<dt>col08：</dt><dd>${obj.col08}</dd>
		</dl>
		<dl>
			<dt>col09：</dt><dd>${obj.col09}</dd>
		</dl>
		<dl>
			<dt>col10：</dt><dd>${obj.col10}</dd>
		</dl>
		<dl>
			<dt>col11：</dt><dd>${obj.col11}</dd>
		</dl>
		<dl>
			<dt>col12：</dt><dd>${obj.col12}</dd>
		</dl>
		<dl>
			<dt>col13：</dt><dd>${obj.col13}</dd>
		</dl>
		<dl>
			<dt>col14：</dt><dd>${obj.col14}</dd>
		</dl>
		<dl>
			<dt>col15：</dt><dd>${obj.col15}</dd>
		</dl>
		<dl>
			<dt>col16：</dt><dd>${obj.col16}</dd>
		</dl>
		<dl>
			<dt>col17：</dt><dd>${obj.col17}</dd>
		</dl>
		<dl>
			<dt>col18：</dt><dd>${obj.col18}</dd>
		</dl>
		<dl>
			<dt>col19：</dt><dd>${obj.col19}</dd>
		</dl>
		<dl>
			<dt>col20：</dt><dd>${obj.col20}</dd>
		</dl>
		<dl>
			<dt>col21：</dt><dd>${obj.col21}</dd>
		</dl>
		<dl>
			<dt>col22：</dt><dd>${obj.col22}</dd>
		</dl>
		<dl>
			<dt>col23：</dt><dd>${obj.col23}</dd>
		</dl>
		<dl>
			<dt>col24：</dt><dd>${obj.col24}</dd>
		</dl>
		<dl>
			<dt>col25：</dt><dd>${obj.col25}</dd>
		</dl>
		<dl>
			<dt>col26：</dt><dd>${obj.col26}</dd>
		</dl>
		<dl>
			<dt>col27：</dt><dd>${obj.col27}</dd>
		</dl>
		<dl>
			<dt>col28：</dt><dd>${obj.col28}</dd>
		</dl>
		<dl>
			<dt>col29：</dt><dd>${obj.col29}</dd>
		</dl>
		<dl>
			<dt>col30：</dt><dd>${obj.col30}</dd>
		</dl>
		<dl>
			<dt>col31：</dt><dd>${obj.col31}</dd>
		</dl>
		<dl>
			<dt>col32：</dt><dd>${obj.col32}</dd>
		</dl>
		<dl>
			<dt>col33：</dt><dd>${obj.col33}</dd>
		</dl>
		<dl>
			<dt>col34：</dt><dd>${obj.col34}</dd>
		</dl>
		<dl>
			<dt>col35：</dt><dd>${obj.col35}</dd>
		</dl>
		<dl>
			<dt>col36：</dt><dd>${obj.col36}</dd>
		</dl>
		<dl>
			<dt>col37：</dt><dd>${obj.col37}</dd>
		</dl>
		<dl>
			<dt>col38：</dt><dd>${obj.col38}</dd>
		</dl>
		<dl>
			<dt>col39：</dt><dd>${obj.col39}</dd>
		</dl>
		<dl>
			<dt>col40：</dt><dd>${obj.col40}</dd>
		</dl>
		<dl>
			<dt>col41：</dt><dd>${obj.col41}</dd>
		</dl>
		<dl>
			<dt>col42：</dt><dd>${obj.col42}</dd>
		</dl>
		<dl>
			<dt>col43：</dt><dd>${obj.col43}</dd>
		</dl>
		<dl>
			<dt>col44：</dt><dd>${obj.col44}</dd>
		</dl>
		<dl>
			<dt>col45：</dt><dd>${obj.col45}</dd>
		</dl>
		<dl>
			<dt>col46：</dt><dd>${obj.col46}</dd>
		</dl>
		<dl>
			<dt>col47：</dt><dd>${obj.col47}</dd>
		</dl>
		<dl>
			<dt>col48：</dt><dd>${obj.col48}</dd>
		</dl>
		<dl>
			<dt>col49：</dt><dd>${obj.col49}</dd>
		</dl>
		<dl>
			<dt>col50：</dt><dd>${obj.col50}</dd>
		</dl>
		<dl>
			<dt>col51：</dt><dd>${obj.col51}</dd>
		</dl>
		<dl>
			<dt>col52：</dt><dd>${obj.col52}</dd>
		</dl>
		<dl>
			<dt>col53：</dt><dd>${obj.col53}</dd>
		</dl>
		<dl>
			<dt>col54：</dt><dd>${obj.col54}</dd>
		</dl>
		<dl>
			<dt>col55：</dt><dd>${obj.col55}</dd>
		</dl>
		<dl>
			<dt>col56：</dt><dd>${obj.col56}</dd>
		</dl>
		<dl>
			<dt>col57：</dt><dd>${obj.col57}</dd>
		</dl>
		<dl>
			<dt>col58：</dt><dd>${obj.col58}</dd>
		</dl>
		<dl>
			<dt>col59：</dt><dd>${obj.col59}</dd>
		</dl>
		<dl>
			<dt>col60：</dt><dd>${obj.col60}</dd>
		</dl>
		<dl>
			<dt>col61：</dt><dd>${obj.col61}</dd>
		</dl>
		<dl>
			<dt>col62：</dt><dd>${obj.col62}</dd>
		</dl>
		<dl>
			<dt>col63：</dt><dd>${obj.col63}</dd>
		</dl>
		<dl>
			<dt>col64：</dt><dd>${obj.col64}</dd>
		</dl>
		<dl>
			<dt>col65：</dt><dd>${obj.col65}</dd>
		</dl>
		<dl>
			<dt>col66：</dt><dd>${obj.col66}</dd>
		</dl>
		<dl>
			<dt>col67：</dt><dd>${obj.col67}</dd>
		</dl>
		<dl>
			<dt>col68：</dt><dd>${obj.col68}</dd>
		</dl>
		<dl>
			<dt>col69：</dt><dd>${obj.col69}</dd>
		</dl>
		<dl>
			<dt>col70：</dt><dd>${obj.col70}</dd>
		</dl>
		<dl>
			<dt>col71：</dt><dd>${obj.col71}</dd>
		</dl>
		<dl>
			<dt>col72：</dt><dd>${obj.col72}</dd>
		</dl>
		<dl>
			<dt>col73：</dt><dd>${obj.col73}</dd>
		</dl>
		<dl>
			<dt>col74：</dt><dd>${obj.col74}</dd>
		</dl>
		<dl>
			<dt>col75：</dt><dd>${obj.col75}</dd>
		</dl>
		<dl>
			<dt>col76：</dt><dd>${obj.col76}</dd>
		</dl>
		<dl>
			<dt>col77：</dt><dd>${obj.col77}</dd>
		</dl>
		<dl>
			<dt>col78：</dt><dd>${obj.col78}</dd>
		</dl>
		<dl>
			<dt>col79：</dt><dd>${obj.col79}</dd>
		</dl>
		<dl>
			<dt>col80：</dt><dd>${obj.col80}</dd>
		</dl>
		<dl>
			<dt>col81：</dt><dd>${obj.col81}</dd>
		</dl>
		<dl>
			<dt>col82：</dt><dd>${obj.col82}</dd>
		</dl>
		<dl>
			<dt>col83：</dt><dd>${obj.col83}</dd>
		</dl>
		<dl>
			<dt>col84：</dt><dd>${obj.col84}</dd>
		</dl>
		<dl>
			<dt>col85：</dt><dd>${obj.col85}</dd>
		</dl>
		<dl>
			<dt>col86：</dt><dd>${obj.col86}</dd>
		</dl>
		<dl>
			<dt>col87：</dt><dd>${obj.col87}</dd>
		</dl>
		<dl>
			<dt>col88：</dt><dd>${obj.col88}</dd>
		</dl>
		<dl>
			<dt>col89：</dt><dd>${obj.col89}</dd>
		</dl>
		<dl>
			<dt>col90：</dt><dd>${obj.col90}</dd>
		</dl>
		<dl>
			<dt>col91：</dt><dd>${obj.col91}</dd>
		</dl>
		<dl>
			<dt>col92：</dt><dd>${obj.col92}</dd>
		</dl>
		<dl>
			<dt>col93：</dt><dd>${obj.col93}</dd>
		</dl>
		<dl>
			<dt>col94：</dt><dd>${obj.col94}</dd>
		</dl>
		<dl>
			<dt>col95：</dt><dd>${obj.col95}</dd>
		</dl>
		<dl>
			<dt>col96：</dt><dd>${obj.col96}</dd>
		</dl>
		<dl>
			<dt>col97：</dt><dd>${obj.col97}</dd>
		</dl>
		<dl>
			<dt>col98：</dt><dd>${obj.col98}</dd>
		</dl>
		<dl>
			<dt>col99：</dt><dd>${obj.col99}</dd>
		</dl>
		<dl>
			<dt>实发工资：</dt><dd>${obj.total}</dd>
		</dl>
		<dl>
			<dt>状态：</dt><dd>${obj.status}</dd>
		</dl>
		<dl>
			<dt>描述：</dt><dd>${obj.description}</dd>
		</dl>
		<dl>
			<dt>部门：</dt><dd>${obj.deptid}</dd>
		</dl>
		<dl>
			<dt>salarytext00：</dt><dd>${obj.salarytext00}</dd>
		</dl>
		<dl>
			<dt>salarytext01：</dt><dd>${obj.salarytext01}</dd>
		</dl>
		<dl>
			<dt>salarytext02：</dt><dd>${obj.salarytext02}</dd>
		</dl>
		<dl>
			<dt>salarytext03：</dt><dd>${obj.salarytext03}</dd>
		</dl>
		<dl>
			<dt>salarytext04：</dt><dd>${obj.salarytext04}</dd>
		</dl>
		<dl>
			<dt>salarytext05：</dt><dd>${obj.salarytext05}</dd>
		</dl>
		<dl>
			<dt>salarytext06：</dt><dd>${obj.salarytext06}</dd>
		</dl>
		<dl>
			<dt>salarytext07：</dt><dd>${obj.salarytext07}</dd>
		</dl>
		<dl>
			<dt>salarytext08：</dt><dd>${obj.salarytext08}</dd>
		</dl>
		<dl>
			<dt>salarytext09：</dt><dd>${obj.salarytext09}</dd>
		</dl>
		<dl>
			<dt>创建人：</dt><dd>${obj.createUser}</dd>
		</dl>
		<dl>
			<dt>创建时间：</dt><dd>${obj.createDate}</dd>
		</dl>
		<dl>
			<dt>修改人：</dt><dd>${obj.modifyUser}</dd>
		</dl>
		<dl>
			<dt>修改时间：</dt><dd>${obj.modifyDate}</dd>
		</dl>

		<div class="divider"></div>
			</div>

	<div class="formBar">
		<ul>
			<li><div class="button"><div class="buttonContent"><button class="close" type="button"><hi:text key="关闭"/></button></div></div></li>
		</ul>
	</div>
</div>
